    int i;
    int j;
    int k;
    i = 7;
    j = 20;
    k = i+j;
    print k;
    printString(" = 7+20\n");
    k = i-j;
    print k;
    printString(" = 7-20\n");
    k = i*j;
    print k;
    printString(" = 7*20\n");
    k = j/i;
    print k;
    printString(" = 7/20\n");    
    k = j%i;
    print k;
    printString(" = 7%%20\n");
    k = -i;
    print k;
    printString(" = -7\n");
    k = i^3;
    print k;
    printString(" = 7^3\n");
